import fs from 'fs';
import path from 'path';
import readline from 'readline';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ANSI escape codes for beautiful styling
const colors = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  cyan: '\x1b[36m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  magenta: '\x1b[35m'
};

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const askQuestion = (query, defaultValue = '') => {
  const displayQuery = defaultValue 
    ? `${colors.bold}${query}${colors.reset} [${colors.cyan}${defaultValue}${colors.reset}]: `
    : `${colors.bold}${query}${colors.reset}: `;
  return new Promise((resolve) => {
    rl.question(displayQuery, (answer) => {
      resolve(answer.trim() || defaultValue);
    });
  });
};

async function runSetup() {
  console.clear();
  console.log(`${colors.cyan}${colors.bold}=============================================================`);
  console.log(`          CAREER-OPS AI JOB SEARCH PIPELINE SETUP`);
  console.log(`=============================================================${colors.reset}\n`);
  console.log(`This interactive installer will configure Career-Ops on your system.`);
  console.log(`It works on ${colors.bold}Windows, Linux, and macOS${colors.reset}.\n`);

  // Detect Host OS
  const isWindows = process.platform === 'win32';
  console.log(`${colors.bold}Detected OS:${colors.reset} ${colors.green}${isWindows ? 'Windows' : 'Linux / macOS'}${colors.reset}\n`);

  // 1. Setup Folder
  const rootDir = __dirname;
  console.log(`${colors.bold}Workspace Directory:${colors.reset} ${colors.yellow}${rootDir}${colors.reset}\n`);

  // 2. Personal Information
  console.log(`${colors.cyan}${colors.bold}--- Step 1: Personal Profile ---${colors.reset}`);
  const fullName = await askQuestion('Your Full Name', 'Jane Smith');
  const email = await askQuestion('Your Email Address', 'jane@example.com');
  const phone = await askQuestion('Your Phone Number', '+1-555-0123');
  const location = await askQuestion('Your Location (City, State/Country)', 'San Francisco, CA');
  const timezone = await askQuestion('Your Timezone (e.g., EST, CST, PST, GMT)', 'PST');
  const visaStatus = await askQuestion('Your Work Visa / Sponsorship Status', 'No sponsorship needed');
  console.log('');

  // 3. Target Roles
  console.log(`${colors.cyan}${colors.bold}--- Step 2: Target Roles & Comp ---${colors.reset}`);
  const primaryRolesInput = await askQuestion('Primary Target Roles (comma-separated)', 'Senior AI Engineer, ML Engineer');
  const primaryRoles = primaryRolesInput.split(',').map(r => r.trim()).filter(Boolean);
  
  const targetComp = await askQuestion('Target Salary Range (Total Comp)', '$150K-$200K');
  const minComp = await askQuestion('Minimum Walk-away Salary', '$120K');
  console.log('');

  // 4. API Key Configuration
  console.log(`${colors.cyan}${colors.bold}--- Step 3: API Credentials ---${colors.reset}`);
  console.log(`Career-Ops uses Google Gemini to evaluate job postings.`);
  console.log(`Get a ${colors.bold}Free Gemini API Key${colors.reset} here: ${colors.magenta}https://aistudio.google.com/apikey${colors.reset}`);
  const geminiKey = await askQuestion('Paste your Gemini API Key (press Enter to skip and add later)');
  console.log('');

  // 5. Resume (CV) Configuration
  console.log(`${colors.cyan}${colors.bold}--- Step 4: Resume Setup ---${colors.reset}`);
  console.log(`Career-Ops tailors your resume automatically for every position.`);
  const resumePath = await askQuestion('Path to your existing CV file (.md or raw text) or press Enter to generate a template');
  console.log('');

  console.log(`${colors.cyan}${colors.bold}--- Step 5: Configuring System Files ---${colors.reset}`);

  // Ensure config folder exists
  const configDir = path.join(rootDir, 'config');
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }

  // Create config/profile.yml
  const profileYmlPath = path.join(configDir, 'profile.yml');
  const profileContent = `# Career-Ops Profile Configuration
# Automatically generated by setup.mjs
# This is the single source of truth for your personal data.

candidate:
  full_name: "${fullName}"
  email: "${email}"
  phone: "${phone}"
  location: "${location}"
  linkedin: "linkedin.com/in/yourprofile"
  portfolio_url: ""
  github: ""
  twitter: ""

target_roles:
  primary:
${primaryRoles.map(role => `    - "${role}"`).join('\n')}
  archetypes:
${primaryRoles.map(role => `    - name: "${role}"\n      level: "Senior"\n      fit: "primary"`).join('\n')}

narrative:
  headline: "${primaryRoles[0] || 'Senior Engineer'} with expertise in modern technologies"
  exit_story: "Looking to bring enterprise automation and cloud engineering expertise to a scaling product team."
  superpowers:
    - "Infrastructure Automation"
    - "System Architecture Design"
    - "Technical Project Scoping"
  proof_points:
    - name: "Key Project"
      url: ""
      hero_metric: "Improved system reliability and operational efficiency"

compensation:
  target_range: "${targetComp}"
  currency: "USD"
  minimum: "${minComp}"
  location_flexibility: "Remote preferred, open to hybrid"

location:
  country: "United States"
  city: "${location.split(',')[0].trim()}"
  timezone: "${timezone}"
  visa_status: "${visaStatus}"

cv:
  output_format: "html"
`;

  fs.writeFileSync(profileYmlPath, profileContent, 'utf8');
  console.log(` ${colors.green}✓${colors.reset} Created profile configuration: ${colors.yellow}config/profile.yml${colors.reset}`);

  // Create .env
  const envPath = path.join(rootDir, '.env');
  const envContent = `# career-ops — Environment Variables
# Automatically generated by setup.mjs

GEMINI_API_KEY=${geminiKey || 'your_gemini_api_key_here'}
# GEMINI_MODEL=gemini-2.5-flash
`;
  fs.writeFileSync(envPath, envContent, 'utf8');
  console.log(` ${colors.green}✓${colors.reset} Created environment file: ${colors.yellow}.env${colors.reset}`);

  // Create portals.yml if missing
  const portalsPath = path.join(rootDir, 'portals.yml');
  const portalsExamplePath = path.join(rootDir, 'templates', 'portals.example.yml');
  if (!fs.existsSync(portalsPath)) {
    if (fs.existsSync(portalsExamplePath)) {
      fs.copyFileSync(portalsExamplePath, portalsPath);
      console.log(` ${colors.green}✓${colors.reset} Initialized scanner configuration: ${colors.yellow}portals.yml${colors.reset}`);
    } else {
      fs.writeFileSync(portalsPath, 'portals: []', 'utf8');
      console.log(` ${colors.green}✓${colors.reset} Initialized empty: ${colors.yellow}portals.yml${colors.reset}`);
    }
  }

  // Create modes/_profile.md if missing
  const profileMdPath = path.join(rootDir, 'modes', '_profile.md');
  const profileMdTemplate = path.join(rootDir, 'modes', '_profile.template.md');
  if (!fs.existsSync(profileMdPath)) {
    if (fs.existsSync(profileMdTemplate)) {
      fs.copyFileSync(profileMdTemplate, profileMdPath);
      console.log(` ${colors.green}✓${colors.reset} Initialized personal narrative mode: ${colors.yellow}modes/_profile.md${colors.reset}`);
    } else {
      fs.writeFileSync(profileMdPath, '# Personal Profile Narrative\n', 'utf8');
    }
  }

  // Create applications.md tracker if missing
  const trackerDir = path.join(rootDir, 'data');
  if (!fs.existsSync(trackerDir)) {
    fs.mkdirSync(trackerDir, { recursive: true });
  }
  const trackerPath = path.join(trackerDir, 'applications.md');
  if (!fs.existsSync(trackerPath)) {
    const trackerHeader = `# Applications Tracker

| # | Date | Company | Role | Score | Status | PDF | Report | Notes |
|---|------|---------|------|-------|--------|-----|--------|-------|
`;
    fs.writeFileSync(trackerPath, trackerHeader, 'utf8');
    console.log(` ${colors.green}✓${colors.reset} Initialized applications tracker: ${colors.yellow}data/applications.md${colors.reset}`);
  }

  // Set up cv.md
  const cvPath = path.join(rootDir, 'cv.md');
  if (resumePath && fs.existsSync(resumePath)) {
    try {
      const originalCv = fs.readFileSync(resumePath, 'utf8');
      fs.writeFileSync(cvPath, originalCv, 'utf8');
      console.log(` ${colors.green}✓${colors.reset} Copied your existing resume to: ${colors.yellow}cv.md${colors.reset}`);
    } catch (e) {
      console.log(` ${colors.red}✗${colors.reset} Error copying resume: ${e.message}`);
    }
  } else if (!fs.existsSync(cvPath)) {
    const cvTemplate = `# ${fullName}

- ${phone} | ${email} | ${location} | linkedin.com/in/yourprofile

## Professional Summary
Experienced technical professional specializing in automation, scalability, and engineering practices.

## Core Competencies
- Technical Solutions Design
- Scripting & Automation
- Systems Architecture

## Experience

### Your Current Company
**Senior Engineer** | 2022 - Present
- Led design and delivery of critical infrastructure scaling projects.
- Collaborated with database and product teams to optimize application latency.

### Your Previous Company
**Systems Engineer** | 2018 - 2022
- Managed and hardened enterprise operating systems and high-availability systems.
- Programmed custom automation scripts to reduce operations overhead.

## Education
- B.Sc. in Computer Science
`;
    fs.writeFileSync(cvPath, cvTemplate, 'utf8');
    console.log(` ${colors.green}✓${colors.reset} Created a standard CV template at: ${colors.yellow}cv.md${colors.reset}`);
  }

  // Create Launchers
  const batchLauncherPath = path.join(rootDir, 'launch-dashboard.bat');
  const shLauncherPath = path.join(rootDir, 'launch-dashboard.sh');

  const batchContent = `@echo off
title Career-Ops Dashboard
cls
echo ========================================================
echo            CAREER-OPS TUI DASHBOARD LAUNCHER
echo ========================================================
echo.
echo [INFO] Setting working directory...
cd /d "%~dp0"
echo [INFO] Workspace root: %CD%
echo.
echo [INFO] Transitioning to dashboard directory...
cd dashboard
echo [INFO] Starting Career-Ops Dashboard...
go run main.go -path ..
if %ERRORLEVEL% neq 0 (
    echo.
    echo [ERROR] Failed to launch the dashboard.
    echo Please make sure Go is installed and configured on your PATH.
    echo If you haven't initialized dependencies, try:
    echo   go mod tidy
    echo.
    pause
)
`;
  fs.writeFileSync(batchLauncherPath, batchContent, 'utf8');
  console.log(` ${colors.green}✓${colors.reset} Created Windows launcher: ${colors.yellow}launch-dashboard.bat${colors.reset}`);

  const shContent = `#!/bin/bash
clear
echo "========================================================"
echo "           CAREER-OPS TUI DASHBOARD LAUNCHER"
echo "========================================================"
echo ""
echo "[INFO] Setting working directory..."
DIR="$( cd "$( dirname "\${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"
echo "[INFO] Workspace root: \$DIR"
echo ""
echo "[INFO] Transitioning to dashboard directory..."
cd dashboard
echo "[INFO] Starting Career-Ops Dashboard..."
go run main.go -path ..
if [ \$? -ne 0 ]; then
    echo ""
    echo "[ERROR] Failed to launch the dashboard."
    echo "Please make sure Go is installed and configured on your PATH."
    echo "If you haven't initialized dependencies, try:"
    echo "  go mod tidy"
    echo ""
    read -p "Press enter to continue..."
fi
`;
  fs.writeFileSync(shLauncherPath, shContent, 'utf8');
  try {
    if (!isWindows) {
      execSync(`chmod +x "${shLauncherPath}"`);
    }
  } catch (e) {
    // Ignore executable permission errors on Windows or locked permissions
  }
  console.log(` ${colors.green}✓${colors.reset} Created Linux/macOS launcher: ${colors.yellow}launch-dashboard.sh${colors.reset}\n`);

  // 6. System Package Verification & Recommendations
  console.log(`${colors.cyan}${colors.bold}--- Step 6: System Prerequisites Check ---${colors.reset}`);
  
  // Check Go
  let hasGo = false;
  try {
    const goVer = execSync('go version', { stdio: 'pipe' }).toString().trim();
    console.log(` ${colors.green}✓${colors.reset} Go Language: ${colors.cyan}${goVer}${colors.reset}`);
    hasGo = true;
  } catch (e) {
    console.log(` ${colors.red}✗${colors.reset} Go Language: ${colors.red}Not found${colors.reset}`);
  }

  // Check Playwright / Node Modules
  let hasPlaywright = fs.existsSync(path.join(rootDir, 'node_modules', 'playwright'));
  console.log(` ${colors.green}${hasPlaywright ? '✓' : '✗'}${colors.reset} Playwright Node Packages: ${colors.cyan}${hasPlaywright ? 'Installed' : 'Missing (needs npm install)'}${colors.reset}\n`);

  // Output Recommendations if anything is missing
  if (!hasGo || !hasPlaywright) {
    console.log(`${colors.yellow}${colors.bold}⚠️  System Improvements Recommended:${colors.reset}`);
    
    if (!hasGo) {
      console.log(`\nTo run the TUI Dashboard, you need ${colors.bold}Go (Golang)${colors.reset}.`);
      if (isWindows) {
        console.log(`  👉 Windows Command (run as Admin in PowerShell):`);
        console.log(`     ${colors.cyan}winget install GoLang.Go${colors.reset}`);
      } else {
        console.log(`  👉 Ubuntu/Debian Command:`);
        console.log(`     ${colors.cyan}sudo apt-get update && sudo apt-get install -y golang${colors.reset}`);
        console.log(`  👉 RHEL/Fedora Command:`);
        console.log(`     ${colors.cyan}sudo dnf install -y golang${colors.reset}`);
        console.log(`  👉 macOS Command (Homebrew):`);
        console.log(`     ${colors.cyan}brew install go${colors.reset}`);
      }
    }

    if (!hasPlaywright) {
      console.log(`\nTo compile resume PDFs, you need to initialize NPM and install Playwright.`);
      console.log(`  👉 Run these commands in your workspace root:`);
      console.log(`     ${colors.cyan}npm install && npx playwright install${colors.reset}`);
    }
    console.log('');
  }

  console.log(`${colors.green}${colors.bold}=============================================================`);
  console.log(`          SETUP COMPLETE! CHOOSE YOUR NEXT STEP:`);
  console.log(`=============================================================${colors.reset}\n`);
  console.log(`1. ${colors.bold}Dashboard TUI:${colors.reset} Launch it using the generated launcher script:`);
  console.log(`   * Windows: Double-click ${colors.cyan}launch-dashboard.bat${colors.reset}`);
  console.log(`   * Linux/macOS: Run ${colors.cyan}./launch-dashboard.sh${colors.reset}`);
  console.log(`2. ${colors.bold}Evaluate a Job Offer:${colors.reset}`);
  console.log(`   * Run: ${colors.cyan}node gemini-eval.mjs "https://link-to-job-posting"${colors.reset}`);
  console.log(`3. ${colors.bold}Search Portals:${colors.reset}`);
  console.log(`   * Run: ${colors.cyan}node scan.mjs${colors.reset}\n`);

  rl.close();
}

runSetup().catch(err => {
  console.error(`${colors.red}Setup encountered an error:${colors.reset}`, err);
  rl.close();
});
